# Generated by Django 4.1.1 on 2022-09-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('fav_artist', models.CharField(max_length=50)),
                ('fav_genre', models.CharField(max_length=50)),
            ],
        ),
    ]
